# Variable 'MONGOCONNECTIONSTRING' was defined in the Variables tab
# Variable 'STAGE' was defined in the Variables tab
# Cron Schedules have been converted using UTC Time Zone and may need to be updated for your location
trigger:
  branches:
    include:
    - refs/heads/main
schedules:
- cron: 0 1 * * *
  branches:
    include:
    - refs/heads/main
name: $(date:yyyyMMdd)$(rev:.r)
jobs:
- job: Job_1
  displayName: Build
  pool:
    name: Eridania
    demands:
    - environment -equals qa
  steps:
  - checkout: self
  - bash: |
        cd scm-qa-automation-py
        python3.9 -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt
        python3.9 -m pytest tests/QAEnvTests/aggregationTests 
    displayName: Run pytest

...